USE [master]
GO

/****** Object:  Database [Fluered]    Script Date: 10/1/2023 6:01:59 PM ******/
CREATE DATABASE [Fluered]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Fluered', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\Fluered.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Fluered_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\Fluered_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Fluered].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Fluered] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Fluered] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Fluered] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Fluered] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Fluered] SET ARITHABORT OFF 
GO

ALTER DATABASE [Fluered] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Fluered] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Fluered] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Fluered] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Fluered] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Fluered] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Fluered] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Fluered] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Fluered] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Fluered] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Fluered] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Fluered] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Fluered] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Fluered] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Fluered] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Fluered] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Fluered] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Fluered] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Fluered] SET  MULTI_USER 
GO

ALTER DATABASE [Fluered] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Fluered] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Fluered] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Fluered] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Fluered] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Fluered] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Fluered] SET QUERY_STORE = ON
GO

ALTER DATABASE [Fluered] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [Fluered] SET  READ_WRITE 
GO

